// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ujiwh80IqzJunHqT_ewbStWPGweKFvM',
    appId: '1:728792097115:web:e0329323b80cab38fd7a7e',
    messagingSenderId: '728792097115',
    projectId: 'flutter-udemy-72d04',
    authDomain: 'flutter-udemy-72d04.firebaseapp.com',
    storageBucket: 'flutter-udemy-72d04.firebasestorage.app',
    measurementId: 'G-89RP879SEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_YafATbD1_a0xi_6Q0NcoW-Kqk-1yfA',
    appId: '1:728792097115:android:2ff66e72fb0866f0fd7a7e',
    messagingSenderId: '728792097115',
    projectId: 'flutter-udemy-72d04',
    storageBucket: 'flutter-udemy-72d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl9ienGuBa6RjuZMNxb7hazRhDVAMqCm4',
    appId: '1:728792097115:ios:11f39182f136fb66fd7a7e',
    messagingSenderId: '728792097115',
    projectId: 'flutter-udemy-72d04',
    storageBucket: 'flutter-udemy-72d04.firebasestorage.app',
    iosBundleId: 'com.example.flutterUdemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ujiwh80IqzJunHqT_ewbStWPGweKFvM',
    appId: '1:728792097115:web:d98ab0758a5fa78efd7a7e',
    messagingSenderId: '728792097115',
    projectId: 'flutter-udemy-72d04',
    authDomain: 'flutter-udemy-72d04.firebaseapp.com',
    storageBucket: 'flutter-udemy-72d04.firebasestorage.app',
    measurementId: 'G-NG2RJG2CVD',
  );
}
